### ISSUE TITLE
Styles are leaking

### ISSUE THREAD

**Issue by JerryI** [ivanceras/svgbob#100]
it injects global styles for SVG, which basically corrupts other SVGs on a page.
![Screenshot 2023-03-21 at 18 16 56](https://user-images.githubusercontent.com/4111822/226689831-2c7c80be-204e-4bcd-b4a2-bb4d1f7512f7.png)

I am using wasm-packed version of SVGBOB
It would be nice have a prefix added to the classes

**Comment by ivanceras** [comment]
Thanks opening this issue @JerryI , this is something that should be a feature in this project.

**Comment by ivanceras** [comment]
This has been fixed in [0.7.0](https://github.com/ivanceras/svgbob/blob/master/Changelog.md) release
