### ISSUE TITLE
docs: radius 2.0 circle is iffy

### ISSUE THREAD

**Issue by zellyn** [ivanceras/svgbob#102]
On the [circle specification page](https://ivanceras.github.io/content/Svgbob/Circles.html), the radius 2.0 circle is rendered like this:
![image](https://github.com/ivanceras/svgbob/assets/33625/eb07a81a-9559-4479-b16a-3262a03fa91b)

The rest are fine. Great, actually!

**Comment by ivanceras** [comment]
[This](https://ivanceras.github.io/content/Svgbob/Circles.html) has now been fixed. It's a changed in the circle with radius 2.0 ascii art, but the docs hasn't been updated in a while.
