### ISSUE TITLE
Choose a file extension for the new file format

### ISSUE THREAD

**Issue by supertxtnet** [ivanceras/svgbob#104]
I think that with this new format there should be a file extension so that specialized tools can be chosen to convert and edit it. Since it is plain text, the base file extension is ".txt" so that general text editing tools still work. However, for more specialized tools it can be something like ".sb.txt" (svgbob on top of text) so that they can be registered for it.

**Comment by ivanceras** [comment]
I use `.bob` or `.md`, or `.txt` depending on its use case. I usually use them inside of `.md` and is pages are generated using cli static site generators. `.md` is recognized in most OS and is opened by text editors by default.
