### ISSUE TITLE
Lines crossing issue

### ISSUE THREAD

**Issue by ipocentro87** [ivanceras/svgbob#105]
Hi all, 
When I try to  do this:
```
 |
---
 |
```
The result SVG shows two lines where the horizontal line appears to be above the vertical one.
However, the other way around doesn't seem to work:
```
-|-
```
as it basically behaves as same as:
```
 |
-+-
 |
 ```
 Is anyone else having the same issue?

**Comment by ivanceras** [comment]
Hello @ipocentro87 , this is an intended effect as it make sense topology wise. In the first figure, the vertical line is much farther to the horizontal line, thus it shouldn't automatically connect. On the other hand in the second figure, the horizontal line is much closer to the vertical line on its side, therefore it automatically connects. Explicitly putting `+` or `|` on the intersection would connect it.

**Comment by ipocentro87** [comment]
Hi @ivanceras , is there an alternative way to write `-|-` but without having those lines crossing?
Example:
```
            //     |||   |||   |||   |||  | |
            //     vvv   vvv   vvv   vvv  | |
            //    +---+ +---+ +---+ +---+ | |
            //    |CSA| |CSA| |CSA| |CSA| | |
            //    +---+ +---+ +---+ +---+ | |
            //    s| |c  | |   | |   | |  | |
            //     | |   | | .-' '-. | |  | |
            //     | |   | '-|---. | | |  | |
            //     | '-------|-. | | | |  | |
            //     '---. | .-' | | | | |  | |
            //     .---|-|-|---|-|-|-|-|--' |
            //     | .-|-|-|---|-|-|-|-|----'
            //     | | | | | .-|-|-|-' |
            //     v v v v v v v v v   v
```

**Comment by ivanceras** [comment]
@ipocentro87 you can use the any of the parenthesis, `(` or `)` to visually indicate the that lines is not connected, like so.

```
            //     |||   |||   |||   |||  | |
            //     vvv   vvv   vvv   vvv  | |
            //    +---+ +---+ +---+ +---+ | |
            //    |CSA| |CSA| |CSA| |CSA| | |
            //    +---+ +---+ +---+ +---+ | |
            //    s| |c  | |   | |   | |  | |
            //     | |   | | .-' '-. | |  | |
            //     | |   | '-|---. | | |  | |
            //     | '---)---|-. | | | |  | |
            //     '---. | .-' | | | | |  | |
            //     .---|-|-|---|-|-|-|-(--' |
            //     | .-|-|-|---|-|-|-|-|----'
            //     | | | | | .-|-|-|-' |
            //     v v v v v v v v v   v
```

Also, in electrical circles lines that just without putting a dot marker is also considered not connected.
