### ISSUE TITLE
Bad dependency in bobsvg/Cargo.toml

### ISSUE THREAD

**Issue by zot** [ivanceras/svgbob#114]
This refers to a local path. Changing it to refer to version `0.61.8` appears to work.

https://github.com/ivanceras/svgbob/blob/a31e1ff5d5047cb0684c3ecbe59e2bdcfe86969a/packages/svgbob/Cargo.toml#L17

**Comment by ivanceras** [comment]
Must have checked in my local setup while developing the code.

**Comment by zot** [comment]
I REALLY like this package but I need to embed HTML in my diagrams (like a list of URLS for a link lablel), so I'm "downgrading" to mermaid. :(

**Comment by ivanceras** [comment]
[Fixed](https://github.com/ivanceras/svgbob/commit/c2f3145500ee768f2d24d1394ca197dd84c0b850)
