### ISSUE TITLE
Properly vectorize close shapes to allow styling

### ISSUE THREAD

**Issue by ivanceras** [ivanceras/svgbob#12]
The shapes are all cramped together in one big path, and it is not possible for further styling.
This is requirement for issue #11

**Comment by virtualirfan** [comment]
Hi @ivanceras:

Can you outline how you envision this getting implemented in case I want to take a stab at it?

**Comment by ivanceras** [comment]
yeah, you can go ahead and implement, I don't have much time working on this project as of the moment.

**Comment by ivanceras** [comment]
This is very hard to accomplish without doing a complete overhaul of the design.
