### ISSUE TITLE
Should unconnected lines be seperate paths? 

### ISSUE THREAD

**Issue by galadran** [ivanceras/svgbob#14]
I really like svgbob and I've started using it to mock up diagrams and automatically include them into my LaTex. However, when I come to do final copies, I'll probably want to tweak the diagrams by hand in Inkscape. [1]

I've noticed that some lines seem to be drawn as part of one huge path, for example: 

![2017-07-10-11 32 17_selection_001_](https://user-images.githubusercontent.com/13476086/28014192-a9865280-6563-11e7-854a-010c0668ab57.png)

Although this can be broken apart, each connected component is then composed of multiple tiny paths which are painful to manipulate.  

![2017-07-10-11 36 31_selection_001_](https://user-images.githubusercontent.com/13476086/28014302-11a4a2ea-6564-11e7-89f2-ff05e12cbaeb.png)

Is this intended or desirable behavior for some other purpose? If not, it would be great to have them as separate path objects in the svg. 

[1] `inkscape -D -z --file=bob_file.svg --export-pdf=bob_out.pdf --export-latex` and then including the generated Tex file.

**Comment by ivanceras** [comment]
Hi,
Unfortunately, svgbob is not ready for an organized svg output yet. The optimization algorithm is not very good yet. It may take a while before it would be ready for that purpose.
