### ISSUE TITLE
Consider release with support of the last stable

### ISSUE THREAD

**Issue by tglman** [ivanceras/svgbob#23]
Hi,

I tried to build the 0.2.* set of version on the rust 1.23.0 and it do not build, I would prefer to see the crates published to build on the stable maybe the feature that need the unstable may be disabled on release, and as well who use unstable is more willing to build from source.

Regards

**Comment by ivanceras** [comment]
@tglman 0.2.7 is now using stable rust. Please check it out.

**Comment by tglman** [comment]
Hi, 

Perfect, could you propagate this downstream, i mean: spongedown if you haven't done yet :)
