### ISSUE TITLE
Escaping characters to have them "verbatim"?

### ISSUE THREAD

**Issue by zverok** [ivanceras/svgbob#24]
Hi there! Awesome project. I wanted to ask if it is possible to somehow tell renderer that "this character is just text"? I am trying to render Ruby's object diagram from the official book:

```
                             +---------+             +-...
                             |         |             |
             BasicObject-----|-->(BasicObject)-------|-...
                 ^           |         ^             |
                 |           |         |             |
              Object---------|----->(Object)---------|-...
                 ^           |         ^             |
                 |           |         |             |
                 +-------+   |         +--------+    |
                 |       |   |         |        |    |
                 |    Module-|---------|--->(Module)-|-...
                 |       ^   |         |        ^    |
                 |       |   |         |        |    |
                 |     Class-|---------|---->(Class)-|-...
                 |       ^   |         |        ^    |
                 |       +---+         |        +----+
                 |                     |
    obj--->OtherClass---------->(OtherClass)-----------...
```

...and the SvgBobRus understands it pretty well, but replaces most of the "O"s with special symbols (note  also it can't guess two arrows under the "Class" at the bottom):
![image](https://user-images.githubusercontent.com/129656/37862894-46569cfa-2f5d-11e8-8123-a24a7929d1f3.png)

**Comment by ivanceras** [comment]
Hi, you can use quotes `"` to tell svgbob that it is just text. 

So, you can do like:

-->"BasicObject"---

**Comment by zverok** [comment]
![image](https://user-images.githubusercontent.com/129656/37868924-8485368a-2fb7-11e8-8f40-5574a94564fe.png)

:(

**Comment by ivanceras** [comment]
This is a bug.

**Comment by gilescope** [comment]
if O is laterally beside [A-Za-z1-9] treat as a word.

**Comment by ivanceras** [comment]
I published a new [release](https://crates.io/crates/svgbob), changing the behavior on how characters should behave. The Demo shown in the README of this project has improved treating characters such as "OoxX" to behave as text when next to a text and treated as drawing element when next to another drawing element that can strongly connect to it.
