### ISSUE TITLE
Crossing diagonals

### ISSUE THREAD

**Issue by xguerin** [ivanceras/svgbob#25]
Hello !

Is there a way to display crossing diagonals ? Example:

```
------------.                
             \ .-------------
              \              
             / '------------>
------------'                
```

The diagonal crossing is incomplete. It would be nice to have access to `X` for that job:

```
------------.                
             \ .-------------
              X              
             / '------------>
------------'                
```

Thanks,

**Comment by ivanceras** [comment]
@xguerin do you have a screenshot of how it looks like right now? It would help to make a quick look

**Comment by ivanceras** [comment]
I can see it now, its ugly. I'll implement it when I have time. For now you can try to use something like these:
```
------------.   .-------------            
             \ /
              X              
             / \
------------'   '------------>        

-----------.
            \   .-------------            
             \ /
              X              
             / \
            /   '------------>  
-----------'

```

**Comment by xguerin** [comment]
Thanks ! Will do

**Comment by ivanceras** [comment]
This has been fixed on version [0.2.8](https://crates.io/crates/svgbob)
This example [code](https://github.com/ivanceras/svgbobrus/blob/master/svgbob/examples/issue25.rs)
will now render like [this](https://github.com/ivanceras/svgbobrus/blob/master/svgbob/examples/issue25.svg)

**Comment by xguerin** [comment]
Awesome. Thanks !

**Comment by ivanceras** [comment]
This is broken on the new releases.
