### ISSUE TITLE
`-->o` is not an arrow

### ISSUE THREAD

**Issue by suhr** [ivanceras/svgbob#27]
Even in `-->o-->` it isn't.

**Comment by ivanceras** [comment]
By design, `--->` is treated as an arrow.

**Comment by suhr** [comment]
But `--->o--->` is not:

![](http://svgur.com/i/6ur.svg)

That's annoying, I want to do something like `*---|--->*` but it doesn't work.

**Comment by ivanceras** [comment]
That arrow with circle used to worked here http://ivanceras.github.io/spongedown-editor/
It looks like the recent changed in how characters are treated as word or drawing element missed this particular one. I'll take a look on this bug.

**Comment by suhr** [comment]
The online editor OOMs my system, I'd rather not use it.

**Comment by ivanceras** [comment]
Now, rendered correctly in recent overhaul changes https://ivanceras.github.io/svgbob-editor/
