### ISSUE TITLE
Difference in rendering with old elm example

### ISSUE THREAD

**Issue by nkh** [ivanceras/svgbob#30]
Hi,  

I notice a different rendering of the sequence:
```
                      .      \ \ '--- The::Latest
                     /|       \ \      \
 With::Some::fantasy  '        \ \      '---- The::Latest::Greatest
                     /|         \ \
         More::Stuff  '          \ '- I::Am::Running::Out::Of::Ideas
                     /|           \
         More::Stuff  '            \
                     /              '--- Last::One
         More::Stuff 
```
in svgbob and https://ivanceras.github.io/elm-examples/elm-bot-lines/

In a terminal the use of  quote "'" rather than dot "."  looks better in ASCII. Could you unify the rendering so both render the same way

If you think I am picky and have an hawk eye, it's because I have drawn most of the example you use in the old version and they grabbed my eye today when I saw this project for the first time.

I think I may steal from you one or two stencils, I like the circles rendering, in fact I like this project very much.

**Comment by ivanceras** [comment]
>  https://ivanceras.github.io/elm-examples/elm-bot-lines/

This is already deprecated and unmaintained.
You can try on this new [link](https://ivanceras.github.io/svgbob-editor/).

The `'` has been reworked to not connect `|` and has been carried over to `.`
You can try this instead:
```

                      .      \ \ '--- The::Latest
                     /|       \ \      \
 With::Some::fantasy  .        \ \      '---- The::Latest::Greatest
                     /|         \ \
         More::Stuff  .          \ '- I::Am::Running::Out::Of::Ideas
                     /|           \
         More::Stuff  .            \
                     /              '--- Last::One
         More::Stuff 
```

**Comment by nkh** [comment]
Hmm, makes sense.  I wrote Asciio so I have to think about changing it in the stencils.

I also noticed that "I::Am::Running::Out::Of::Ideas" is not rendered properly in the new version while it was in the old one, which I  understand is deprecated.

**Comment by ivanceras** [comment]
> I also noticed that "I::Am::Running::Out::Of::Ideas" is not rendered properly in the new version while it  was in the old one, which I understand is deprecated.

Lately I was using `:` as vertical broken lines, I haven't polished the part where it is used as text when surrounded with other text. I'll definitely polished this stuff.

**Comment by ivanceras** [comment]
> I wrote Asciio so I have to think about changing it in the stencils.

This project is hugely inspired by Asciio, your usage of combining the ascii makes more sense than the other ones i see. I took most parts of your asciio examples and tuned the generated svg from there.

It's good to hear that you are still maintaining that project.

**Comment by nkh** [comment]
"Still maintaining" is a big word, it seems that I have not commited anything since 2015.  But I am always surprised when I see Asciio generated drawings, it seems it's used more than I thought. It may gain traction when I finally write a curses interface rather than the gtk interface. A simpler packaging would help windows user, Camelbox did that but it's broken, linux users are more lucky.

But you can have a look here, I have plans, when I have an extra life, to write the next version.
https://github.com/nkh/Asciio-2.0/issues svgbob, and a few other renderers are there.
