### ISSUE TITLE
Converting to PNG(using rsvg-convert) drops lines

### ISSUE THREAD

**Issue by K4zuki** [ivanceras/svgbob#32]
### Problem

With using `rsvglib(as rsvg-convert)` on Mac, conversion is not great; output is dropping "lines".
I am not sure this is `rsvglib` matter or `svgbob`.

#### Conditions

- MacOS
- svgbob 0.3.1
- rsvg-convert version 2.40.16

#### Input

`input.txt`:
```
               o VDD
               |
              +++
              | |
              +++    +
  THRESHOLD    |   + |\    +-------+                 +
  o------------------+ \   |       |                 |\
               |     |  +--| R     |                 | \
               *-----+ /   |       | +---------------+  +o----------o
               |   - |/    |       | |               | /  OUTPUT
              +++    +     |       | |               |/
              | |          |       | |               +
              +++    +     |       | |     o DISCHARGE
               |   + |\    |       | |     |
               *-----+ \   |       | |   |'
  nTRIGGER     |     |  +--| S  nQ o-*---+  NPN
  o------------------+ /   |       |     |`>
               |   - |/    +---o---+       |
              +++    +         |           |
              | |              |           |
              +++              |           |
               |               |           |
               *---------------------------+
               |               |
               o GND           |
  nRESET                       |
  o----------------------------+

```
`$ input.txt -o svg.svg`
`$ rsvg-convert -f png svg.svg -o png.png`

#### Output

SVG output(screenshot) is great like
<img width="599" alt="2018-09-25 22 48 07" src="https://user-images.githubusercontent.com/9379328/46018639-4d4a7780-c115-11e8-8342-4aa21ffcecb3.png">
while conversion to png is like
![png](https://user-images.githubusercontent.com/9379328/46018178-39eadc80-c114-11e8-9f9b-f47d9c4b32af.png)

**Comment by ivanceras** [comment]
This has to do with and version librsvg which is used in some older linux distro like ubuntu16.04 where it doesn't seem to process the css definition in svg(which the lines' and paths' stroke are defined) . I noticed in preview image in ubuntu 16 where the generated svg from svgbob looks like this, but when viewed with inkscape, it will display correctly.

I will have to add the settings in svgbob to inline the style, such that older svgviewer will be able to see the stroke and fill of svg objects.

**Comment by K4zuki** [comment]
@ivanceras 
FYI, `librsvg=2.42.2_2` worked.

**Comment by K4zuki** [comment]
@ivanceras 
FYI again,
I found changing from `<style>` to `<style type="text/css">` worked with **`rsvg-convert = 2.40.13`** on Ubuntu16.04(WSL).

* librsvg is installed via apt.

**Comment by ivanceras** [comment]
Oh cool. I will add that to the svg generator.

**Comment by ivanceras** [comment]
Oh cool. I will add that to the svg generator.
