### ISSUE TITLE
"Other example" doesn't link up rounded corners correctly

### ISSUE THREAD

**Issue by tabatkins** [ivanceras/svgbob#36]
The "Other Example" you provide has a lot of shapes that don't connect properly, like:

```
           .-.      
          |   |     
       .---------.  
      |           | 
       '---------'  
          |   |     
           '-'     
```

In this example, the ends of *both* lozenges don't connect to their sides; you instead have to widen things so they connect:

```
          .---.      
          |   |     
      .-----------.  
      |           | 
      '-----------'  
          |   |     
          '---'     
```

I'm not sure if this is intended behavior or not, but it affects a *lot* of images in this example page, so I assume it must have worked at some point.

**Comment by tabatkins** [comment]
Hmm, given the "Mixed Rounded & Square Corners" example, I'm assuming that the extra-separated version was intended to be recognized as a rounder corner.

**Comment by ivanceras** [comment]
The rounded corner is using the `'` , `.` and `'` while sharp corner is using `+` . First example has far more separate distance which requires a bit more of explicit behavior, therefore it is not sought. The examples are not yet adjusted yet.
