### ISSUE TITLE
shape doesn't close between + and * vertically

### ISSUE THREAD

**Issue by QiangF** [ivanceras/svgbob#39]
Normally there is no gap between adjacent + and *, eg:

    --+*

but if the two are vertically aligned, there is a gap: 

      *----.
    --+ ab |
      | ab |
    --*----'
      +

also, when simply vertically align the two, * is treated as a character:

    |
    +
    *

**Comment by ivanceras** [comment]
@QiangF characters such as `+, *, . ` have a lower signal intensity . You may need to use characters like `|` and `-` to explicitly mean a connection to the `*`. Balancing the signal intensity is quite hard since it affects all other formation.
```
---*

  *----.
--| ab |
  | ab |
--*----'
  |

|
|
*
```
