### ISSUE TITLE
Bug with arrows?

### ISSUE THREAD

**Issue by virtualritz** [ivanceras/svgbob#49]
These are two a screenshots from the live editor. See what happens with the right arrow going down?
Looks not intended/like a bug to me.
<img width="240" alt="Screen Shot 2020-03-02 at 20 30 04" src="https://user-images.githubusercontent.com/387036/75710411-d2e83480-5cc4-11ea-97b9-b811d00dd7ee.png">
<img width="234" alt="Screen Shot 2020-03-02 at 20 29 56" src="https://user-images.githubusercontent.com/387036/75710423-d7145200-5cc4-11ea-8b6a-a422ccb5f122.png">

**Comment by ivanceras** [comment]
@virtualritz Thanks for reporting, with the new core architectural change to support tag styling bug like these is expected to occur.

**Comment by virtualritz** [comment]
No wuckers! :) I am super excited about styling support!

**Comment by habamax** [comment]
is this related:

![image](https://user-images.githubusercontent.com/234774/93747595-9ac42700-fbff-11ea-8e96-643b68324c1e.png)

![image](https://user-images.githubusercontent.com/234774/93747639-aa437000-fbff-11ea-905e-1c3db822324f.png)

**Comment by habamax** [comment]
It is rendered correctly in firefox and chrome though.

Issue is in Internet Explorer 11 and in PDF generated with asciidoctor-pdf + asciidoctor-diagram


[svgs.zip](https://github.com/ivanceras/svgbob/files/5254363/svgs.zip)

**Comment by ivanceras** [comment]
Yes, this is a bug. I will try to work on it, if I have some time.

**Comment by ivanceras** [comment]
Some of the arrow marker is already fixed on the new releases. The arrows in the flow chart example is still there.
Please checkout the new improvements at this new [demo site](https://svgbob-editor.netlify.app/)

**Comment by ivanceras** [comment]
This has been fixed in the new release.
