### ISSUE TITLE
Text alignment is off

### ISSUE THREAD

**Issue by offbynull** [ivanceras/svgbob#50]
```
<--+----+----+----+----+----+----+----+----+-->
   |    |    |    |    |    |    |    |    | 
 "-4" "-3" "-2" "-1"  "0" "+1" "+2" "+3" "+4"
```

Results in...

![image](https://user-images.githubusercontent.com/6354978/76700984-46118380-6693-11ea-8a76-1cca71a83715.png)

Notice how the alignment is off.

**Comment by offbynull** [comment]
I should mention that the quotes around the text are to escape the dash and the plus signs

**Comment by ivanceras** [comment]
@offbynull I just pushed out a new text escaping. After escaping the double quotes will become a whitespace. You probably need to visually align the text and the drawing like this:

```bob
<--+----+----+----+----+----+----+----+----+-->
   |    |    |    |    |    |    |    |    | 
  "-4" "-3" "-2" "-1" "0"  "+1" "+2" "+3" "+4"
```

**Comment by offbynull** [comment]
Thank you!
