### ISSUE TITLE
[Question] How to go about dividing a circle into a pie chart

### ISSUE THREAD

**Issue by dmayle** [ivanceras/svgbob#57]
Hi,
I keep trying to draw a representative pie chart, but circles are very finicky, and every time I change them up a little, the circle breaks.  Could you give pointers on how to create a circle that looks like a pie chart?

**Comment by ivanceras** [comment]
unfortunately, there is no convenient way to express a pie chart into an ascii diagram and vice versa. The algorithm for inferring  circles is hardcoded  for a set of characters that forms a circle, found in this [code](https://github.com/ivanceras/svgbob/blob/master/svgbob/src/map/circle_map.rs). Inferring arcs is also limited to the 4 perpendicular quadrants of the circle, so it's very limited to what it can do.
