### ISSUE TITLE
Arrows appearing where they shouldn't

### ISSUE THREAD

**Issue by Kimbatt** [ivanceras/svgbob#60]
When editing, arrowheads sometimes appear at the end of lines.
(I encountered this issue with the online editor)

Steps to reproduce:

Start with an empty editor, paste this:
```
      |
      |
---------------->
      |
      |
```
Correct result:
![image](https://user-images.githubusercontent.com/29901058/88523620-85b08a80-cff8-11ea-90a2-ae7aa5b73dee.png)

Change to this (edit that one character):
```
      |
      v
---------------->
      |
      |
```
The result is still correct:
![image](https://user-images.githubusercontent.com/29901058/88523669-95c86a00-cff8-11ea-824a-40323e5fcb65.png)

Undo it, or change that one character back:
```
      |
      |
---------------->
      |
      |
```
The image is incorrect:
![image](https://user-images.githubusercontent.com/29901058/88523669-95c86a00-cff8-11ea-824a-40323e5fcb65.png)

After this, type a letter here:
```
      |
      |a
---------------->
      |
      |
```
Image:
![image](https://user-images.githubusercontent.com/29901058/88523868-ecce3f00-cff8-11ea-9b2e-2928d8c4196f.png)

Then erase/undo it:
```
      |
      |
---------------->
      |
      |
```
An arrow appeared at the bottom:
![image](https://user-images.githubusercontent.com/29901058/88523916-ffe10f00-cff8-11ea-9f33-a4415dfc799f.png)

After refreshing the page and pasting the same text back again, it works.

**Comment by ivanceras** [comment]
This seems like delayed rendering bug. The debounce implementation is quite crude at the moment, therefore you are seeing a render from the previous text.

**Comment by ivanceras** [comment]
I just pushed out several updates. Please check if this is still an issue.
