### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by nkh** [ivanceras/svgbob#62]
cat ~/nadim/devel/repositories/perl_modules/P5-App-Asciio/lib/App/Asciio.pm
| svgbob > test.svg

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }', /home/nadim/.cargo/registry/src/github.com-1ecc6299db9ec823/svgbob_cli-0.4.2/src/main.rs:98:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

file is probably close to this one https://github.com/nkh/P5-App-Asciio/blob/master/lib/App/Asciio.pm

**Comment by bjorn3** [comment]
That means that `Asciio.pm` is not valid utf-8. What is the output of `file ~/nadim/devel/repositories/perl_modules/P5-App-Asciio/lib/App/Asciio.pm`?

**Comment by nkh** [comment]
There was indeed a non utf -8 characters that were weeded out with "grep -axv '.*' file"

new files is here if you want to see how it is rendered, most Asciio drawings render nicely.

https://github.com/nkh/P5-App-Asciio/blob/master/lib/App/Asciio.pm

I noticed that one lien with a tab and spaces didn't render too nicely, is there a way to say how many characters a tab is?

**Comment by ivanceras** [comment]
I will close this now, as this seems not specific to svgbob
