### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by vladimyr** [ivanceras/svgbob#68]
Hi @ivanceras 

Thanks for building this cool tool 👍 

I've made a Homebrew formula for `svgbob` CLI, but, as of writing this, `svgbob`'s latest release is marked as `0.5.0-alpha.6`, [preventing it from inclusion in the core tap](https://github.com/Homebrew/homebrew-core/pull/66270#pullrequestreview-545504925). 
I agreed to move it to a personal tap → https://github.com/vladimyr/homebrew-vladimyr/blob/00b11f4/Formula/svgbob.rb and let you know to feel free resubmit it once `svgbob` gets its first stable release 😉

**Comment by ivanceras** [comment]
This may take a while. I'd been meaning to release 0.5.0 as soon as I restore the original features before the architectural overhaul.

**Comment by vladimyr** [comment]
Don't, by any means, feel pushed to do it sooner due to me taking initiative here! Take your time and when the moment comes it will get revisited. 🤝

**Comment by vladimyr** [comment]
`svgbob` formula is now available inside core tap: Homebrew/homebrew-core#80544 🎉
