### ISSUE TITLE
Svg file returned from url

### ISSUE THREAD

**Issue by billthefarmer** [ivanceras/svgbob#70]
What would be useful would be a method of returning a svg image from a request URL containing the source text, similar to SciWeavers site to return an image from Latex text (http://www.sciweavers.org/tex2img.php?eq=\sum_{i=1}^{n}x_{i}^{2}&bc=cornsilk&fc=black&im=jpg&fs=24&ff=arev).

![Latex](http://www.sciweavers.org/tex2img.php?eq=\sum_{i=1}^{n}x_{i}^{2}&bc=cornsilk&fc=black&im=jpg&fs=24&ff=arev)

**Comment by ivanceras** [comment]
@billthefarmer that would be doable, but I don't have resources to provide such a server. If there is somebody willing to donate a server, I would build it.

**Comment by billthefarmer** [comment]
You've already got one in your svgbob editor page. You appear to have compiled your rust sources to web assembly and used a JavaScript wrapper to provide the page functionality. the JavaScript appears to include a function to take a text string and return an SVG image by calling web assembly functionality.

If you did what I suggest it might generate more traffic than GitHub are happy with if it became popular.

**Comment by ivanceras** [comment]
If doing all the execution in client-side with the webassembly code, then the output of the url would be a DOM which is not an svg image. This generated dom can not be simply used in an `img src=` tag. This would then be embedded in webpages which I think is not a straightforward way to do it. It would be akin to embedding a tweet with all the needed wasm binary and assets rather than generating a rendered image server side.

**Comment by billthefarmer** [comment]
If you have an account on [Sourceforge](https://sourceforge.net/), you can use [Developer Web](https://sourceforge.net/p/forge/documentation/Developer%20Web%20Services/). I used to have some stuff on there, but moved it to here. It can be horribly slow, but it works, good enough for testing. I noticed for some things hosted on there that get a lot of traffic, like [OpenGApps](https://sourceforge.net/projects/opengapps/), it works very well.

**Comment by ivanceras** [comment]
You can go ahead and do it yourself. This project is opensource, the build script and everything is in here.
