### ISSUE TITLE
Refrac ion

### ISSUE THREAD

**Issue by traverseda** [ivanceras/svgbob#75]
![image](https://user-images.githubusercontent.com/2125828/125631121-a7d13e38-692c-48e2-a6d3-3a02e88379f3.png)
![image](https://user-images.githubusercontent.com/2125828/125630946-db792f39-c810-4fcc-9e9c-8c992886e02d.png)

**Comment by ivanceras** [comment]
can't replicate this, It reads `Refraction` on my end. What browser are you using?

**Comment by traverseda** [comment]
Firefox. It appears that some kind of frame is blocking the letters, I have an somewhat odd aspect ratio (I'm using my backup laptop as my main one stopped taking a charge) so that might be where that problem is coming from. If you want to fix this you can try using responsive mode to set the page's screen size to 1366x768.

![image](https://user-images.githubusercontent.com/2125828/126792217-d431c6dc-0f75-43d2-a65f-b648c39ef971.png)

**Comment by ivanceras** [comment]
This looks like just a visual bug on the presentation on the browser. I don't think it affects the generated svg. You can try to use the Download Svg button on the side and open the generated svg with Inkscape or some other browser.

**Comment by traverseda** [comment]
Yep, on further inspection it's just a bug in the html/css layout. Not terribly important.
