### ISSUE TITLE
Rendering of 'O' near 'X'

### ISSUE THREAD

**Issue by PHHENS** [ivanceras/svgbob#81]
Dear developpers,

Rendering of 'O' near 'X' adds a pigtail to 'O'.
Example :
SOX are
   Orange
renders :
![image](https://user-images.githubusercontent.com/36993124/134820161-6b024d2b-cc62-4e13-b63f-79c7047634ee.png)

Thanks for helping.

**Comment by mbarkhau** [comment]
I think the general rule here is: you can avoid that characters are interpreted as part of a shape if you put them in quotes.

https://mbarkhau.keybase.pub/asciigrid/#vvF;AOAOA;SCTFfEYFSCBAAfELHIXGFBBAjQoJ

That's of course just a quick fix. Whether or not this behaviour should change in svgbob is a different question.

**Comment by PHHENS** [comment]
OK, this resolve quickly my issue.
