### ISSUE TITLE
Question: create a bigger circles 

### ISSUE THREAD

**Issue by tobiasdroessler** [ivanceras/svgbob#97]
How do I create larger circles ... ? 

in the online editor sample i had a view at the circles. I need a huger circle than the 12 one in the sample down at at the button. the scale up by  copy/paste a line and column in the middle did not work.

It was a little bit confusing why each circle size is built up different.

**Comment by ivanceras** [comment]
Hi, the circles are defined using an ascii art of what looks like a circle in this [code](https://github.com/ivanceras/svgbob/blob/master/packages/svgbob/src/map/circle_map.rs) 
There is no good algorithm that can do this automatically, especially if the circles has smaller radius. If you have an ascii art for larger circles, then it can be added in the circle map.

**Comment by tobiasdroessler** [comment]
thank you for the finger to the code ...   I really like your project and enjoy using svgbob to improve documentations...   hopefully there is some time on my side and i can have a look into your code in remaining 2022. 

**_THANK YOU_** 👍  for creation and sharing this great project.  I will close this thread.
